version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elknet
    restart: always
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.1.2
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5044:5044
    # command: bash -c "logstash -f /usr/share/logstash/pipeline/logstash.conf && bin/logstash-plugin install logstash-input-beats"
    networks:
      - elknet
    restart: always
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.2
    ports:
      - 5601:5601
    networks:
      - elknet
    restart: always

networks:
  elknet:
    driver: bridge
volumes:
  data:
    driver: local
